### ISSUE TITLE
Why still develop gnu hurd ? It's a lack of time. 

### ISSUE THREAD

**Issue by LifeIsStrange** [joshumax/hurd#1]
Gnu hurd is useless will be forever, why gnu hurd exist ? Why not Improve Linux which is already GPL. 
I think it's stupid.

**Comment by CVipulS** [comment]
As major 1.0 release of HURD for most OSs is as yet unattained, survey studying usefulness is far off in the future to speculate anything today itself. Linux can be compared with Mach in the HURD's initial implementation stack. Linux being monolithic, rather than doing separation of concerns that's suggested by HURD's model, is indeed stupid. But as it's promoters keep saying, Linux happened because otherwise they'd have to keep waiting for HURD based GNU OS. In other words, they wanted what was thought of as an OS back then itself, rather than working on the next iteration of what qualifies as an OS. Imho, iterating on what qualifies as an OS must happen at least until Moore's law holds, but it's a question every developer answers for oneself. Carnegie Mellon's Mach is alright for GNU, just as it was for OS X, so why just stop at improving Linux, as besides Mach, there's Haiku, the BSDs, RISC OS, ..

**Comment by LifeIsStrange** [comment]
Thanks for your good answer against my pretentious post. 
Your answer is very interesting. 

I speak bad english so I have not all understund but from what I understund of your answer you say that Linux was an error an that an OS will separate task with micro kernels rather than be monolithic. 
Why ? Nobody have proven that micro kernels are better than monolithic, and Linux is not monolithic, Linux is monolithic modular \* 
The primary Noise of micro kernels is that they increase dramatically the systems calls and the latency.  Same Windows kernel is not micro kernel, it is hybrid. 
The actual architecture of HURD is not revolutionary. 
Yes there is BSDS, darwin, risc os, haïku, beos, etc...  But what is the utility ? Why separate the human force in différents projects which have the same finality?
HURD will never have good hardware support so it will never be used it's a fact. The different architecture not Offset this fact. Linux have 10000 developers, HURD can't compete. 
The only interest of developping HURD is for the beauty of developping an OS, it's artistic, Fascinating. But will never be used :/ we need to unifie the developers and cooperate for create the Best kernel of the World (Linux)  for the good of the free software, the humanity and for destroy the spywares and prisons that are. Windows and Mac OS. 
Sorry for my bad english.

**Comment by CVipulS** [comment]
Calling Linux an error is far-fetched. More like it's vested interest were different from others vested interest. So the answer to your why is because for comparing kernel, current HURD implementation uses Mach as kernel, i. e. HURD should run atop Mach rather than being Mach or Linux, or whichever your preferred kernel is. Or in more other words, its concerns are different from those of the kernel, even though it's still on the subject of OS. I can't get into much details of kernel variants, but when I noticed HURD, the first thing it cleared was it separated those concerns in particular that bloated the kernel code in the name of being monolithic. You certainly are right about the variant of Linux's monolithic kernel, but that much detail is it's maintainers subject.
Freedom of evolution is for those developers to choose for themselves who commit to it, despite knowing it's not revolution.
The utility is in the choices prioritised by each separate effort. Also pacing HURD's initial implementation's development with the underlying kernel, rather than a revolutionarily paced moving target such as Linux, should make it easier for fewer developers to shape up HURD, before patching Linux, etc. as per learnings from it. The hope from separate projects is to avoid the "same finality", as one size fits all approaches were popular in the generations dominated by dictatorial mindsets.
Hardware or driver support from vendors, say like NVidia is their own business, I am afraid I havn't any position on that. In the developers per line of code race, Linux was known to compete with Minix before Tanenbaum retired, but again, updated statistics is a whole business in itself. As kernel is a technical subject, let's stick with how HURD should be dragged into Linux comparison despite Mach being the only implementation's underlying kernel at present.
Android, a kind of Linux, is known for labelling spyware prison as A/B testing. As for being virtuous as compared to spyware and prison, the Linux promoters fail to admit the fullname must be GNU/Linux. As for humanity, FSF and others are doing their best to keep walled gardens in check.
I've tried to cling to points you've given, but sorry if I got carried away in the extreme opposite direction while merely exhibiting it's possible that other facets of truth might just as well be respectable.

**Comment by LifeIsStrange** [comment]
Sorry for the late late ! 
You say "current HURD implementation uses Mach as kernel, i. e. HURD should run atop Mach rather than being Mach or Linux, or whichever your preferred kernel is. Or in more other words, its concerns are different from those of the kernel, even though it's still on the subject of OS." I don't understund, so one Day HURD will May use Linux and be "atop" what does it mean ? Hurd will be at the kernel what LLVM is at the compilers ? 
"Or in more other words, its concerns are different from those of the kernel, even though it's still on the subject of OS."?? In what it's concerns are different ? I'm really curious 

After you say "The utility is in the choices prioritised by each separate effort." why separate efforts ? It's reinventing the wheel ! 

"Also pacing HURD's initial implementation's development with the underlying kernel, rather than a revolutionarily paced moving target such as Linux, should make it easier for fewer developers to shape up HURD, before patching Linux, etc. as per learnings from it."
Because I speak bad english I have not really understund, you say that HURD will have the same utility than MINIX ? To learn easyly how work an OS ? 

"The hope from separate projects is to avoid the "same finality", as one size fits all approaches were popular in the generations dominated by dictatorial mindsets." I don't understund again, all the OS have the same finality, making the perfect OS with ultimate security /performance /usability /stability /powerefficiency /innovations / artficial intelligence généralist. 
It's universel as finality. 
It's the philosophy which can differate (Windows want to be a prison for the good of the Microsoft Shareholders and the bad of the humanity, BSDs wants to be free but allow proprietary software to reuse,Linux and hurd have the same philosophy, be full free. 

"as one size fits all approaches were popular in the generations dominated by dictatorial mindsets" what is an approache ? It's abstract
Of which you think with dictatorial mindsets ? Linus torvalds ? 

"Android, a kind of Linux, is known for labelling spyware prison as A/B testing. As for being virtuous as compared to spyware and prison, the Linux promoters fail to admit the fullname must be GNU/Linux" false, Android AOSP is full open source (GPL indeed) Google have not the choice, it's the applications atop Android which are spyware (Google play service, Chrome, etc) 
You can use many ROMS which are full opensource, I use cyanogenmod on my oneplus one for example and I Write actually with it and Firefox mobile. 
I think also that GNU/Linux is a wrong name, actually the Linux os is not Just gnu /linux, it's Linux + gnu software + KDE software + Android software + non gnu/KDE affiliated free software (VLC, libreoffice, Firefox, etc) + proprietary software. 
The Just name should be POSIX/linux. 
But Just Linux work also because when we say Linux, we say obviously posix, BUT Linux with WINE is a particular case ^^ because it can run Windows softwares ! 
GNU is essential it's true but it's not an OS, Just a big piece of an enormous OS. And Linux is Just the core of this os.

**Comment by saxbophone** [comment]
@LifeIsStrange I think the team developing Hurd are doing so for the fun of it, more than anything else. I think that is as good a reason as any. That and the distinction between Linux being a monolithic kernel vs Hurd's ambitious Microkernel architecture.

**Comment by LifeIsStrange** [comment]
I agree :)
